In [13]:
import numpy as np

In [14]:
rho = np.random.rand(5, 1)
y = np.array([[1], [1], [0], [1], [0]])
print(rho)
print(y)

[[0.26372921]
 [0.81660623]
 [0.51923691]
 [0.67848628]
 [0.63086877]]
[[1]
 [1]
 [0]
 [1]
 [0]]


In [15]:
rho[y==1]

array([0.26372921, 0.81660623, 0.67848628])